config/routes.rb
Rails.application.routes.draw do
  get 'users/register'
  post 'users/create'
  get  'users/destroy'
  get 'users/users'

  resources :users
  get 'static_page/venue'
  get 'static_page/speakers'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'static_page#overview'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

def hello
	    render html: "hello world"
	end

end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def overview
  end
  def speakers
  end
  def venue
  end
  def login
  end
  def signup
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def register
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: ' Registered successfully.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Details was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Registration successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<!-- Whubs.com - Download Free Responsive Website Layout Templates designed on HTML5 CSS3,Bootstrap which are 100% Mobile friendly. w3Hubs all Layouts are responsive cross browser supported, best quality world class designs. -->
<!DOCTYPE html>
<html>
<head>
	<title>Simple Footer In Html - w3hubs.com</title>
<meta charset="UTF-8">
  <meta name="description" content="Free Web tutorials">
  <meta name="keywords" content="HTML,CSS,XML,JavaScript">
  <meta name="author" content="W3HUBS">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="footer.css">
</head>
<body>
   
   <div class="w3hubs-footer">
   	  
   	  <div class="w3hubs-icon">
   	  	<ul>
   	  		<li><a href="https://www.facebook.com/h2oai/" target="black"><i class="fa fa-facebook"></i></a></li>
   	  		<li><a href="https://github.com/h2oai" target="black"><i class="fa fa-github"></i></a></li>
   	  		<li><a href="https://twitter.com/h2oai" target="black"><i class="fa fa-twitter"></i></a></li>
   	  		<li><a href="https://www.instagram.com/h2o.ai/" target="black"><i class="fa fa-instagram"></i></a></li>
   	  		<li><a href="https://www.youtube.com/user/0xdata" target="black"><i class="fa fa-youtube-play"></i></a></li>
   	  	</ul>
   	  </div>
   	  <div class="w3hubs-nav">
   	  	<ul>
   	  		<li><a href="#">About Us</a></li>
   	  		<li><a href="#">The Team</a></li>
   	  		<li><a href="#">News</a></li>
   	  		<li><a href="#">Communities</a></li>
   	  		<li class="p1"><a href="#">Contact Us</a></li>
   	  		

   	  	</ul>
   	  </div>
   	  <div class="w3hubs-nav1">
   	  	<ul>
   	  		<li><a href="#">Resources</a></li>
   	  		<li><a href="#">Documentation</a></li>
   	  		<li><a href="#">Events</a></li>
   	  		<li><a href="#">Webinars</a></li>
   	  		
   	  		
   	  	</ul>
   	  </div>

   	  
   </div>

   <div class="footer-end">
   	  <p>Designed By: <a href="https://www.h2o.ai/">H2O.ai.com</a></p>
   </div>
</body>
</html>

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<!-- Created By CodingNepal -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Responsive Navbar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <link rel="icon" type="image/x-icon" href="../event.png">
  </head>
  <body  style="margin:0 ;padding:0">
    <nav>
      <input type="checkbox" id="check">
      <label for="check" class="checkbtn">
        <i class="fas fa-bars"></i>
      </label>
      <label class="logo">𝕖𝕧𝕖𝕟𝕥𝕚𝕗𝕪</label>
      <ul>
        <li>
          
          <%= link_to "overview", root_path %><a href="/"></a>
        </li>
        <li>
          <%= link_to "speakers", static_page_speakers_path %><a href="/"></a>
        </li>
        <li>
          <%= link_to "venue", static_page_venue_path %><a href="/"></a>
        </li>
        <li >
          <%= link_to "register" , users_register_path %><a href="/"></a>
        </li>
        <li >
          <%= link_to "Participants" , users_url %><a href="/"></a>
        </li>



    
        

</ul>
 
</nav>

    
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
  <%= render 'layouts/footer' %>
</html>

app/views/static_page/overview.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title></title>
</head>
<body style="margin:0 ;padding:0">





	
<%= image_tag("company/back.jpg", :height=>728,:width=>1838, :crop=>"fill",:position=> "relative")%>


<br><br>
<marquee direction="right" bgcolor="yellow" scrolldelay=1  height=25 vspace=2px><b>Welcome to H<sub>2</sub>o.ai virtual meet </b></marquee>
<!-- <marquee direction = "up">The direction of text will be from bottom to top.</marquee> -->

<div style="padding-left: 50px ;background-color: white">
<p style="text-align: center;"><font color="red" face="Verdana, Geneva, sans-serif" size="+10">A conference for creators like you:</font></p>
<br><br>
<h3><b>Details:</b></h3><br>
<p>
<font  size="+1" >
AI is unlocking new potential for every enterprise. Organizations are using AI and machine learning technology to inform business decisions, predict potential issues, and provide more efficient, customized customer experiences. We will walk through some real use cases we have been a part of across a variety of industries such as finance, retail, and healthcare as well as the impact AI brought to these businesses.
</p>
</font><br><br>
<font  size="+1" >
<b>A few of the companies use cases we will discuss are:</b><br>
<ul  style="list-style-type:disc;padding-left: 20px">
	<li>-AT&T</li>
	<li>-PWC</li>
	<li>-Bill.com</li>
	<li>-G5</li>
</ul></font><br><br>



<div class="row">
  <div class="column" style="float: left; width: 70%;">
  	<p>
	    <font  size="+1" >
H2O.ai is a visionary leader in AI and machine learning and is on a mission to democratize AI for everyone. We believe that every company can become an AI company, not just the AI Superpowers. We are empowering companies with our leading AI and Machine Learning platforms, our expertise, experience and training to embark on their own AI journey to become AI companies themselves. All companies in all industries can participate in this AI Transformation.<br><br>

Tune into this virtual meetup to learn how companies are transforming their business with the power of AI and where to start.
       </font>
    </p>
  </div>
  <div class="column" style="float: left; width: 29%; ">
  	<marquee direction="down" bgcolor="orange" >
        <font color="green">
  		<p style="text-align: center;">Thursday, July 16, 2020<br>
        11:00 AM to 12:00 PM GMT+5:30<br><br>

        Online event
        </p>
        </font>
  	</marquee>
  </div>
</div>
</div>

<br><br><br>
<div>
<center><svg width="7em" height="7em" viewBox="0 0 16 16" class="bi bi-mic" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M3.5 6.5A.5.5 0 0 1 4 7v1a4 4 0 0 0 8 0V7a.5.5 0 0 1 1 0v1a5 5 0 0 1-4.5 4.975V15h3a.5.5 0 0 1 0 1h-7a.5.5 0 0 1 0-1h3v-2.025A5 5 0 0 1 3 8V7a.5.5 0 0 1 .5-.5z"/>
  <path fill-rule="evenodd" d="M10 8V3a2 2 0 1 0-4 0v5a2 2 0 1 0 4 0zM8 0a3 3 0 0 0-3 3v5a3 3 0 0 0 6 0V3a3 3 0 0 0-3-3z"/>
</svg></center>  
<br>
<center><b><font size="+2">Our Speakers</font></b></center> 
<br>
<center>

	<p>
<font size="+1">
-<b>Parul Pandey</b>, Data Science Evangelist and Kaggle Grandmaster, H2O.ai<br>
-<b>Shivam Bansal</b>, Senior Data Scientist and Kaggle Grandmaster, H2O.ai
</font>
	</p>
</center>
</div>
<br><br>
<p style="padding-left: 50px"><font size="+1">Attendees</font></p>
<div style="padding-left: 50px">
	<div class="row row-cols-1 row-cols-md-3">
  <div class="col mb-4">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Swastika</h5>
        <p class="card-text">Member</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Satwiz</h5>
        <p class="card-text">Member</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">vamshi.k</h5>
        <p class="card-text">Member </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">chandra shekhar</h5>
        <p class="card-text">organizer</p>
      </div>
    </div>
  </div>
   <div class="col mb-4">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Niharika</h5>
        <p class="card-text">co-organizer</p>
      </div>
    </div>
  </div>
   <div class="col mb-4">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">sai kiran.B</h5>
        <p class="card-text">promoter</p>
      </div>
    </div>
  </div>
</div>
</div>


</body>
</html>

app/views/static_page/speakers.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
		 body { background: #4d94ff; }

	</style>
</head>
<body>
	
  <center style="padding-top: 50px"><i class="fa fa-microphone fa-5x" aria-hidden="true"></i></center>
	
	<div style="padding-left: 50px;padding-right: 50px" >
		<center><font size="+3" style="color: red">Your speakers Line-up</font> </center>
		<%= image_tag("company/2.png")%>
	<p style="padding-top: 50px"><font size="+2" color="black"><b>Parul Pandey</b></font>&nbsp;&nbsp;<br><br><font size="+1" color="black">follow on: &nbsp;&nbsp;<a href="https://in.linkedin.com/in/parulpandeyindia" style="background: none"><i class="fa fa-linkedin fa-3x" aria-hidden="true"></i></a></font>
		<br>
		<a href="https://sites.google.com/view/parul-pandey/home" style="background: none;text-decoration: none"><font color="indigo">www.parulpandey.com</font></a>
<br>
<br>
	<p style="color: green"><b>Bio:</b></p>	
Parul is a Data Science Evangelist here at H2O.ai. She combines Data Science , evangelism and community in her work. Her emphasis is to spread the information about H2O and Driverless AI to as many people as possible, She is also an active writer and has contributed towards various national and international publications.</p>

<br>
<br>

<div style="float: right;">
<%= image_tag("company/1.png")%>
</div>
<br>
<br>
<div>
	 <div style="float: right; padding-right: 30px">
<p><font size="+2" color="black"><b>Shivam Bansal</b></font><br>
Data Scientist at H2O.ai<br>

Singapore</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div style="float: right;padding-right: 200px">
	<font size="+1" color="black">follow on:</font><br>
<a href="https://twitter.com/shivamshaz" style="background: none"><i class="fa fa-twitter fa-3x" aria-hidden="true"></i></a>&nbsp;
<a href="https://www.linkedin.com/in/shivambansal1/" style="background: none"><i class="fa fa-linkedin fa-3x" aria-hidden="true"></i></a>&nbsp;
<a href="https://github.com/shivam5992" style="background: none"><i class="fa fa-github fa-3x" aria-hidden="true"></i></a>&nbsp;
<br>
<a href="http://www.shivambansal.com/" style="background: none;text-decoration: none"><font color="indigo">www.shivambansal.com</font></a>
<br>
<a href="https://www.kaggle.com/shivamb" style="background: none;text-decoration: none"><font color="brown"> www.kaggle.com</font></a>
</div>
<br><br>


</p>
<br>
<br>
<div >
<p style="color: green"><b>Bio:</b></p>	
	Masters from National University of Singapore - Business Analytics and Data Science,
	Full Stack Data Scientist with background in Computer Science,<br>
	Worked in Healthcare, Insurance, Retail, and Social Media domains

<br><br>
</div>
</div>
</div>
</body>
</html>

app/views/static_page/venue.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Title of the document</title>
    <style>
      .blink {
      animation: blinker 0.6s linear infinite;
      color: #1c87c9;
      font-size: 30px;
      font-weight: bold;
      font-family: sans-serif;
      }
      @keyframes blinker {  
      50% { opacity: 0; }
      }
      .blink-one {
      animation: blinker-one 1s linear infinite;
      }
      @keyframes blinker-one {  
      0% { opacity: 0; }
      }
      .blink-two {
      animation: blinker-two 1.4s linear infinite;
      }
      @keyframes blinker-two {  
      100% { opacity: 0; }
      }
    </style>
  </head>
  <body>
    <p class="blink">Blinking text</p>
    <p class="blink blink-one">CSS blinking effect for opacity starting with 0%</p>
    <p class="blink blink-two">CSS blinking effect for opacity starting with 100%</p>
  </body>
</html>

app/views/users/_form.html.erb
<div class="col-md-2"><div>
  


<div class="col-md-8">
<%= form_with(model: user, local: true) do |form| %>
  <div class="container">
     <div class="row">
            <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
              <div class="form-group">
                <%= form.label :name %>
                <%= form.text_field :name %>
              </div>

              <div class="form-group">
                <%= form.label :email %>
                <%= form.text_field :email %>
              </div>
              <div class="form-group">
                <%= form.label :phone %>
                <%= form.text_field :phone %>
              </div>

              <div class="actions">
                <%= form.submit :register%>
              </div>
            </div>
      </div>
  </div>
<% end %>
<div>

<div class="col-md-2"><div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registration', users_register_path %>

app/views/users/register.html.erb
<h1>New Registration</h1>


<body>


<%= render 'form', user: @user %>

<%= link_to 'Go to Participants List', users_path %>


</body>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>